publishDir = "public_html"

theme = "hyde"
enableGitInfo = false
baseURL = "/"

[params]
  themeColor = "theme-base-0d"
  layoutReverse = true
  urlEnglish = "https://cstm.cs.kuleuven.be/"
  urlNederlands = "https://ovi.cs.kuleuven.be/nl/"

DefaultContentLanguage = "en"

[languages]
	[languages.nl]
		title = "Onderwijs, Vakdidactiek Informatica."
		languagename = "Nederlands"
		[languages.nl.params]
			description = "Onderwijsmethodologie. Vakdidactiek CW."
			TrContents = "Inhoud"
		[languages.nl.Menus]
		  main = [
		  	  {Name = "Home", URL = "/nl/"},
		      {Name = "Verslagen", URL = "/nl/reports"},
		      {Name = "Onderzoek", URL = "/nl/research"},
		      {Name = "Leden", URL = "/nl/members"}
		  ]

	[languages.en]
		title = "Computer Science Teaching Methodology."
		languagename = "English"
		[languages.en.params]
			description = "Computing Education. Course didactics."
			TrContents = "Contents"
		[languages.en.Menus]
		  main = [
		  	  {Name = "Home", URL = "/"},
		      {Name = "Reports", URL = "/reports"},
		      {Name = "Research", URL = "/research"},
		      {Name = "Members", URL = "/members"}
		  ]
